const BUGS = [
    {
        "no": "#22",
        "type": "问题",
        "title": "无法进行签到",
        "desc": "我在进行签到时，提示签到今天已签到，无法进行签到。",
        "status": "不予修复",
        "date": "2026-05-07 21:08 UTC+8",
        "report_player": "start3pro"
    },
    {
        "no": "#21",
        "type": "问题",
        "title": "无法使用CDK",
        "desc": "我在使用CDK时，提示CDK无效，无法使用。",
        "status": "已修复",
        "date": "2026-04-01 11:31 UTC+8",
        "fixed_date": "2026-04-03 13:58 UTC+8",
        "report_player": "kpi_pvp_pro10"
    },
    {
        "no": "#20",
        "type": "问题",
        "title": "循声守卫的相关成就语言文件缺失",
        "desc": "在成就中，冒险模块关于循声守卫的相关成就语言文件缺失，导致成就无法正常显示，显示为了翻译键名。",
        "status": "已修复",
        "date": "2026-03-05 22:16 UTC+8",
        "fixed_date": "2026-03-05 22:51 UTC+8",
        "report_player": "system_mini"
    },
    {
        "no": "#19",
        "type": "问题",
        "title": "无法加入服务器",
        "desc": "我在加入服务器时，提示要绑定QQ账号，无法加入服务器。",
        "status": "特意设计为之",
        "date": "2026-02-22 19:56 UTC+8",
        "report_player": "cklyr91",
        "official_message": "这是服务器的强制项，绑定QQ账号后才能加入服务器。",

    },
    {
        "no": "#18",
        "type": "问题",
        "title": "区块加载异常",
        "desc": "在游戏过程中，我遇到了一个从y0直达y319的区块，的情况，但是下面都是水。",
        "status": "无法修复",
        "date": "2026-01-31 09:28 UTC+8",
        "report_player": "kpi_pvp_pro10",
        "official_message": "这应该是Minecraft的地形生成错误，我们无法修复",
    },
    {
        "no": "#17",
        "type": "问题",
        "title": "部分村民交易界面偶尔闪退关闭",
        "desc": "与村民打开交易界面时，有概率莫名自动关闭界面，需要重新点击才能正常打开交易。",
        "status": "已修复",
        "date": "2025-12-13 16:48 UTC+8",
        "fixed_date": "2026-01-05 09:20 UTC+8",
        "report_player": "qi_pian"
    },
    {
        "no": "#16",
        "type": "问题",
        "title": "网络延迟过高",
        "desc": "在游戏过程中，网络延迟非常的高，高达4198ms，极其影响游戏体验，不过其他玩家没有这个问题。",
        "status": "不予修复",
        "date": "2025-11-20 23:16 UTC+8",
        "report_player": "cm2ecm2ce",
        "official_message": "这是你的个人问题，我们无法修复。",
    },
    {
        "no": "#15",
        "type": "问题",
        "title": "我在战利品宝箱中找到了违规物品",
        "desc": "我在战利品宝箱中找到了违规物品，带有锋利144级的钻石剑和效率75级的铁斧，这在原版中是不可能的。",
        "status": "特意设计为之",
        "date": "2025-09-05 22:01 UTC+8",
        "report_player": "qi_pian",
        "official_message": "这是服务器的的特性，属于正常现象。",
    },
    {
        "no": "#14",
        "type": "问题",
        "title": "我是生存模式，但是我却能打开创造背包",
        "desc": "我在生存模式下，但却能打开创造背包，虽然不能拿出任何物品，但是这让我无法正常进行游戏。",
        "status": "无法修复",
        "date": "2025-08-25 13:51 UTC+8",
        "report_player": "kpi_pvp_pro10",
        "official_message": "这是一个已知问题，我们无法修复，请重新加入服务器再试。",
    },
    {
        "no": "#13",
        "type": "问题",
        "title": "登陆后被留在出生点",
        "desc": "我在登陆后，会被留在出生点，而不是回到上次退出的位置，影响我的游戏体验。",
        "status": "已修复",
        "date": "2025-07-11 15:26 UTC+8",
        "fixed_date": "2025-07-12 07:42 UTC+8",
        "report_player": "qi_pian"
    },
    {
        "no": "#12",
        "type": "问题",
        "title": "服务器无法通过VPN代理连接",
        "desc": "玩家在使用VPN代理连接服务器时，无法正常连接，无法正常进入游戏。",
        "status": "不予修复",
        "date": "2025-05-30 23:16 UTC+8",
        "report_player": "cm2ecm2ce"
    },
    {
        "no": "#11",
        "type": "问题",
        "title": "瞭望塔生成在大海之中",
        "desc": "我在海上划船时，发现瞭望塔生成在大海之中，而不是在陆地。",
        "status": "无法修复",
        "date": "2025-04-07 11:59 UTC+8",
        "report_player": "kpi_pvp_pro10"
    },
    {
        "no": "#10",
        "type": "问题",
        "title": "TPA提示信息占位符异常",
        "desc": "TPA提示信息占位符异常，显示为%player%，而不是玩家的名称。\n提示信息：\n[PixelAdventure] 你已向 %player% 发送过传送请求",
        "status": "无法修复",
        "date": "2025-03-24 14:29 UTC+8",
        "report_player": "qwei101010e"
    },
    {
        "no": "#9",
        "type": "问题",
        "title": "低版本无法进入服务器",
        "desc": "玩家在使用低版本客户端时，无法正常进入服务器，疑似是版本兼容插件没有生效",
        "status": "已修复",
        "date": "2025-03-08 17:21 UTC+8",
        "fixed_date": "2025-03-11 19:23 UTC+8",
        "report_player": "youn110011",
        "official_message": "这应该是ViaRewind插件的问题",
    },
    {
        "no": "#8",
        "type": "问题",
        "title": "主城菜单无法使用",
        "desc": "主城的菜单无法使用，玩家点击按钮后没有反应，无法传送到子服。",
        "status": "无法修复",
        "date": "2025-02-22 17:51 UTC+8",
        "report_player": "mone1en_"
    },
    {
        "no": "#7",
        "type": "问题",
        "title": "无法正常进入子服",
        "desc": "BungeeCord代理服务端出现未知故障无法正常工作，玩家一直无法连接子服，多次检查配置、端口、安全组、插件及重启服务均无效。",
        "status": "无法修复",
        "date": "2025-01-12 17:51 UTC+8",
        "report_player": "broad"
    },
    {
        "no": "#6",
        "type": "问题",
        "title": "新年期间遭恶意炸服攻击，出生点被毁坏",
        "desc": "服务器跨年期间遭受SKYNET恶意炸服攻击，出生点地形被彻底摧毁，出现大量岩浆\n并带有广告计分板：\n!!!TERMINATED BY SKYNET!!! —> Mountains of Lava Inc. —> Please email any concerns to: molcomplaints@***********.com（已做屏蔽处理）\n修改了大量游戏规则\n1. 关闭死亡不掉洛\n2. 开启不显示命令反馈\n3. 开启死亡后立即重生\n4. 关闭日夜交替",
        "status": "已修复",
        "date": "2025-01-01 17:24 UTC+8",
        "fixed_date": "2025-01-01 19:40 UTC+8",
        "report_player": "mone1en_"
    },
    {
        "no": "#5",
        "type": "问题",
        "title": "主城命令方块指令配置错误",
        "desc": "后台修改主城下方命令方块指令时操作失误，意外配置成/kill @e，导致全服玩家无法靠近主城。",
        "status": "已修复",
        "date": "2024-12-13 17:23 UTC+8",
        "fixed_date": "2024-12-13 22:51 UTC+8",
        "report_player": "system_mini"
    },
    {
        "no": "#4",
        "type": "问题",
        "title": "纯原版客户端无法正常进入服务器",
        "desc": "使用无模组纯原版Java客户端登录服务器时，由于客户端缺少ForgeEndertech模组，导致无法正常进入服务器。",
        "status": "已修复",
        "date": "2024-11-13 11:53 UTC+8",
        "fixed_date": "2024-11-13 12:21 UTC+8",
        "report_player": "kmort114514"
    },
    {
        "no": "#3",
        "type": "问题",
        "title": "Tab在线列表默认配色与背景融合难以辨识",
        "desc": "Tab玩家列表原生文字颜色偏浅，和天空/环境背景视觉重叠，玩家昵称看不清，昼夜场景下都存在辨识困难问题。",
        "status": "已修复",
        "date": "2024-10-04 12:44 UTC+8",
        "fixed_date": "2024-10-09 13:07 UTC+8",
        "report_player": "mubu12138"
    },
    {
        "no": "#2",
        "type": "问题",
        "title": "自动化农场模组与反作弊插件冲突",
        "desc": "服务器1.20.2测试阶段，加装自动化农场模组后，与现有反作弊插件产生严重兼容性冲突，直接造成服务器高负载卡顿。",
        "status": "已修复",
        "date": "2024-10-02 22:52 UTC+8",
        "fixed_date": "2024-10-06 17:09 UTC+8",
        "report_player": "chenty"
    },
    {
        "no": "#1",
        "type": "问题",
        "title": "在满血状态下会出现意外扣血",
        "desc": "玩家在满血状态下，玩家会意外扣血，导致游戏体验下降\n详细描述：\n我在吃食物，饱食度已经回满，开始恢复血量，在血量回复满后，过一段时间，会意外扣血",
        "status": "已修复",
        "date": "2024-09-27 14:22 UTC+8",
        "fixed_date": "2024-10-03 12:29 UTC+8",
        "report_player": "mubu12138"
    }
];